jwt:
  secret: ${JWT_SECRET:?SET_ENVIOMENT_JWT_SECRET_IN_SYSTEM}
  expiration-day: ${JWT_EXPIRATION_DAY:?SET_ENVIOMENT_JWT_EXPIRATION_DAY_IN_SYSTEM}
spring:
  profiles: prod
  datasource:
    url: ${DATA_BASE_URL:?SET_ENVIOMENT_DATA_BASE_URL_IN_SYSTEM}
    driver-class-name: org.postgresql.Driver
    username: ${DATA_BASE_USERNAME:?SET_ENVIOMENT_DATA_BASE_USERNAME_URL_IN_SYSTEM}
    password: ${DATA_BASE_PASSWORD:?SET_ENVIOMENT_DATA_BASE_PASSWORD_URL_IN_SYSTEM}
    data: classpath:*sql/data.sql
    schema: classpath:*sql/schema.sql
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate