cloudinary:
  cloud_name: ${CLOUDINARY_NAME:?SET_ENVIOMENT_CLOUDINARY_NAME}
  api_key: ${CLOUDINARY_KEY:?SET_ENVIOMENT_CLOUDINARY_NAME}
  api_secret: ${CLOUDINARY_SECRET:?SET_ENVIOMENT_CLOUDINARY_NAME}
jwt:
  secret: ${JWT_SECRET:?SET_ENVIOMENT_JWT_SECRET_IN_SYSTEM}
  expiration-access-minutes: ${JWT_EXPIRATION_ACCESS_MINUTES:?SET_ENVIOMENT_JWT_EXPIRATION_ACCESS_MINUTES_IN_SYSTEM}
  expiration-refresh-minutes: ${JWT_EXPIRATION_REFRESH_MINUTES:?SET_ENVIOMENT_JWT_EXPIRATION_REFRESH_MINUTES_IN_SYSTEM}
spring:
  profiles: prod
  datasource:
    url: ${DATA_BASE_URL:?SET_ENVIOMENT_DATA_BASE_URL_IN_SYSTEM}
    driver-class-name: org.postgresql.Driver
    username: ${DATA_BASE_USERNAME:?SET_ENVIOMENT_DATA_BASE_USERNAME_URL_IN_SYSTEM}
    password: ${DATA_BASE_PASSWORD:?SET_ENVIOMENT_DATA_BASE_PASSWORD_URL_IN_SYSTEM}
    data: classpath:*sql/data.sql
    schema: classpath:*sql/schema.sql
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  mail:
    username: {MAIL_LOGIN:?SET_ENVIOMENT_MAIL_LOGIN}
    password: {MAIL_PASSWORD:?SET_ENVIOMENT_MAIL_MAIL_PASSWORD}
    properties:
      mail:
        debug: false