export const GET_CUSTOMER_INFO = 'GET_CUSTOMER_INFO';
export const OPEN_MAIL = 'OPEN_MAIL';
export const OPEN_NOTIFICATIONS = 'OPEN_NOTIFICATIONS';
export const OPEN_USER_PROFILE = 'OPEN_USER_PROFILE';
